cambios = 'NEO-ELIASBOT BETA\n\n-Comando lol creado\n-Creado changelog\n-Comando insulto\n-Evento elias creado\n-Evento lol/un lol creado\n-Llevo desde las 9 haciendo esto ayuda por favor como hago para que reproduzca musica alguien digame ya no aguanto este sufrimiento saquenme de aqui pablo me tiene en su sotano programando al neoelias para reemplazar al elias de carne y hueso'

elias = [
    'elias',
    'No subo gordas',
    'Tortigas marinas',
    'No me la e jalado desde que juego adopme',
    'No hay como la libertad de ser',
    'Voy a ser padre en una boda en roblots',
    'Hola preciosa',
    'Me bañe y me heche jabon en el ojo',
    'Quien para culiar',
    'لن يصدقوني يا صديقي ، أنت تبدو رائعًا جدً',
    'Víctor hijo de la vrga',
    ';;play sitatir',
    'Me dices como bailar, Massimo?',
    'Banda, como se llama el anime donde sale un jabali con espada?',
    'Chigas a tu madre ',
    'No me cago para un tiro ',
    'Dime donde para partirte tu madre ',
    'No simpre pudes satisfaser a todo aquel que beses',
    'Hora de iniciar toda la prra tarea para salvar el semestre',
    'Quiero culiar',
    ':angry:',
    'Empieza a gemir *',
    'Owo kiss @Boccheems',
    'A buscar waifus',
    'Tengo miedo del vicio',
    'No me manden al anexo',
    'Mi tía no quiere sacar la botella de tequila',
    'Pinche pezon lo tengo tieso',
    'Pinches coreanas',
    'Por ti bb me volveria furro',
    'Ptm si tengo ganas de coger',
    'Me voy a bañar, ahí se ven todos, en especial a las mamás solteras con dinero suficiente para comprar la Xbox series X. \nVrga jajaja\nLa mamá de Rene',
    'A huevo soy pendejo',
    'Quiero que alguien me de una vrguiza para que se me quite lo pendejo',
    'Elias no esta listo para nada',
    'Quedas advertido',
    'P de pinche pablo pitudo',
    'No soy Elias',
    'Pinche Ramiro',
    'Existen maestros como Jovita y otros como el pendejo de Ramiro',
    'PUTO RAMIRO HIJO DE SU PUTA MADRE, PARA QUE ANDA MAMANDO EN SU PRRA ACTIVIDAD SI DE TODOS MODOS ME LA VOY A PASAR POR LOS HUEVOS',
    'Tremenda tula',
    'PTM PUTO RAMIRO',
    'eto? :point_right: :point_left:',
    'QUE ALGUIEN SILENCIE EL MICRO DE VALERIA',
    'Alguien me hace un cheems?',
    'UwU',
    'Pinche ricardo me fui a extra en primero',
    'Damisela permitame meterle una manzana en la boca y chuparle el siempre sucio hasta sentir la sidra',
    'De un vrgazo te regreso al kinder',
    'Perry el orto rico',
    'Si fuera furro tu serias la primera zorra que me cogeria',
    'Yo jalo hasta donde diga empuje',
    'Me desviare del camino de ser un hombre o una mujer pero nunca en el camino de ser un humano',
    'Te voy a desmembrar pinche Cesar',
    'Yo despues de descubrir que el clitoris es un boss de terraria',
    'Que ganas de ser un lobo y tener una coneja cachonda',
    'I so horny',
    'Pancreas era un continente?',
    'Sabias que el culo produce los 3 estados de la materia?',
    'Nigga',
    'Banda no se si puedo con esto :(',
    'ADMAPMDP}WMED',
    'Solo estoy esperando a mi amada',
    'Quedas advertido',
    'AAAAAAAAAAAAA',
    'Te quiero mucho'
]

insulto =['negro', 'nigga', 'puta', 'chinga tu madre joto', 'te gusta el arroz con popote', 'veta a la verga',
 'putas mujeres', 'putos judios', 'putos israelitas', 'putos negros', 'el elias se la come',
 'a cuanto el kilo de verga', 'yo solo quiero amor', 'putos blancos', 'putos africanos', 'putos sodomitas',
 'putos mancos', 'putos discapacitados', '¿En qué se parecen las mujeres a las baldosas? en que las dos se pisan',
 '¿En qué se parecen las mujeres a las pelotas? en que a las dos se les pega',
 '¿Qué hace una mujer fuera de la cocina? Turismo',
 've a hacerme un sandwich elfa :v',
 'a la cocina pta :vvv']

pablo = ['pablo', 'pablo?', 'pablo-kun', 'pa-pablo', 'quien es ese guapo', 'pinche pablo guapo', 'pablo chapulin', 'traiganme a pablito', 'don chapulin', 'no digan pablo']

lol = [
    'lol', 
    'callate', 
    'pls no', 
    'dejen el vicio',
    'UN PINCHE LOLASO',
    'ni me gankeas a la verga',
    'lole',
    'https://youtu.be/kvhUNv59XdY',
    'yo antes tenía un amigo pero hace unos años desapareció',
    'main lux',
    'ya terminaste tu tarea?',
    'te voy a coger',
    'inviten',
    'un dota 2',
    'a ver',
    'te tqm por favor no juegues lol',
    'No grasias',
    'perdió su vida en el lol',
    'Quien fue? Román? Alan? Massimo?',
    'ya están grandecitos we ya porfa',
    'main renekton',
    'main pyke',
    'main teemo',
    'main morgana',
    'main vladimir',
    'un lolaso',
    'un baropepas'
]

uwu = [
    'UwU',
    'no uwus',
    'el uwu esta prohibido en este servidor',
    'tqm']

matarse = [
    'Estas bien bro?',
    'No te mates',
    'Quieres hablar?',
    'Necesitas ayuda?',
    'Bro no te mates por fabor',
    'Todo bien?',
    'Alguien ayude a mi pana',
    'Eliasbot te ama no te mates por favor']