elias = [
    'elias',
    'No subo gordas',
    'Tortigas marinas',
    'No me la e jalado desde que juego adopme',
    'No hay como la libertad de ser',
    'Voy a ser padre en una boda en roblots',
    'Hola preciosa',
    'Me bañe y me heche jabon en el ojo',
    'Quien para culiar',
    'لن يصدقوني يا صديقي ، أنت تبدو رائعًا جدً',
    'Víctor hijo de la vrga',
    ';;play sitatir',
    'Me dices como bailar, Massimo?',
    'Banda, como se llama el anime donde sale un jabali con espada?',
    'Chigas a tu madre ',
    'No me cago para un tiro ',
    'Dime donde para partirte tu madre ',
    'No simpre pudes satisfaser a todo aquel que beses',
    'Hora de iniciar toda la prra tarea para salvar el semestre',
    'Quiero culiar',
    ':angry:',
    'Empieza a gemir *',
    'Owo kiss @Boccheems',
    'A buscar waifus',
    'Tengo miedo del vicio',
    'No me manden al anexo',
    'Mi tía no quiere sacar la botella de tequila',
    'Pinche pezon lo tengo tieso',
    'Pinches coreanas',
    'Por ti bb me volveria furro',
    'Ptm si tengo ganas de coger',
    'Me voy a bañar, ahí se ven todos, en especial a las mamás solteras con dinero suficiente para comprar la Xbox series X. \nVrga jajaja\nLa mamá de Rene',
    'A huevo soy pendejo',
    'Quiero que alguien me de una vrguiza para que se me quite lo pendejo',
    'Elias no esta listo para nada',
    'Quedas advertido',
    'P de pinche pablo pitudo',
    'No soy Elias',
    'Pinche Ramiro',
    'Existen maestros como Jovita y otros como el pendejo de Ramiro',
    'PUTO RAMIRO HIJO DE SU PUTA MADRE, PARA QUE ANDA MAMANDO EN SU PRRA ACTIVIDAD SI DE TODOS MODOS ME LA VOY A PASAR POR LOS HUEVOS',
    'Tremenda tula',
    'PTM PUTO RAMIRO',
    'eto? :point_right: :point_left:',
    'QUE ALGUIEN SILENCIE EL MICRO DE VALERIA',
    'Alguien me hace un cheems?',
    'UwU',
    'Pinche ricardo me fui a extra en primero',
    'Damisela permitame meterle una manzana en la boca y chuparle el siempre sucio hasta sentir la sidra',
    'De un vrgazo te regreso al kinder',
    'Perry el orto rico',
    'Si fuera furro tu serias la primera zorra que me cogeria',
    'Yo jalo hasta donde diga empuje',
    'Me desviare del camino de ser un hombre o una mujer pero nunca en el camino de ser un humano',
    'Te voy a desmembrar pinche Cesar',
    'Yo despues de descubrir que el clitoris es un boss de terraria',
    'Que ganas de ser un lobo y tener una coneja cachonda',
    'I so horny',
    'Pancreas era un continente?',
    'Sabias que el culo produce los 3 estados de la materia?',
    'Nigga',
    'Banda no se si puedo con esto :(',
    'ADMAPMDP}WMED',
    'Solo estoy esperando a mi amada',
    'Quedas advertido',
    'AAAAAAAAAAAAA',
    'Te quiero mucho',
    'Di no al acaso',
    'Pinche perro desgraciado',
    'Que tan etico es mandarle mensaje a alguien que pidió una recarga y me quede con su ticket?',
    'Nooooo papuuu :''v',
    ':smiling_imp:',
    'no mamen',
    'Nmms banda, este camión no va para el centro',
    'Nmms\nCreo que me gustan señoras',
    'Como dijo mac miler\nGuau Guau Guau Guau  Guau',
    'No, fuck you bitch',
    'Im sorry mrs Jackson',
    'Ojalá hubieran sido mecos en vez del spoiler que me trague',
    'A veces tienes que cerrar una puerta para abrir una ventana',
    'Uno siempre regresa a donde fue feliz',
    'Querer es poder, y si no puedes, es por que no quieres lo suficiente',
    'Tener contactos es fundamental para ser grande en mexico',
    'Ando bien encafeinado y soy una bomba de emociones',
    'Cesar rasista?',
    'Si me gustan las pollas',
    'Los tqm',
    'Y entonces el universo dijo\nTe amo\npor que tu eres el amor',
    'Este perro no come de cualquier carne',
    'Me acaban de ofrecer coca',
    'Ayuda, 2 señoras hijas de la chingada quieren coger',
    'Tengo la oportunidad\nDe ponerla o no',
    'Bendiciones a todos, los quiero mucho',
    'Como se llama el señor que hace parodias de peliculas de disney\npero contrata gente chaparra\nenana\npara hacer las parodias',
    'Tengo disfuncion erectil\nY un excel que terminar',
    'En lo que que tu vienes yo ya voy de regreso',
    'Les chupo el pene a todos, pero por favor, un algo',
    'Los tqm a todos bola de torombolines',
    'No lleven mota, este plan tiene que salir bien',
    'Rápido rapido\nTécnicas para ligar en el camión',
    'Un plan no bien estructurado tiende a fallar',
    'Quiero pene\nAAAAAAAAAAA',
    'Elias is no more',
    'Necesito una moto, me voy a hacer un pikiblainder',
    'Tengo ganas de follar',
    'CAAAAN YOUUU FEEEL MY HEEEARTT',
    'Tu me pelas la papaya? 👉 👈',
    'Fuk yu nigga',
    'el sol me gana en tamaño pero no en lo caliente',
    'Nomamen banda\nMe encule 😋\nDe la doctora\nMe hizo sacarle la lengua y decirle A',
    'No entiendo ahora el mundo\nNo comprenden el amor',
    'Puto roqui, se sabe todas las de badbuni',
    'Te voy a funar',
    'Todo hombre vuelve a donde fue feliz\nAdopt me me llama',
    'Me metieron la vrga\nMe hubiera metido a cucea',
    'No soy Oscar para darte termino medio',
    'Mañana examen de mecanica en el Valle VFG 🤑',
    'El Covenant me llamo comandante supremo',
    'Hora de secuestrar monos',
    'Nomas no se pasen de cangreburger',
    'Cundo vaya a erectus voy a decir "Me da 100 pesos de sexo?"',
    'Boing de mota',
    'Wee\nVuelvete\nHomosexual',
    'Mendigar cariño no es lo correcto'
]

insulto = [
    'negro',
    'nigga',
    'puta',
    'chinga tu madre joto',
    'te gusta el arroz con popote',
    'veta a la verga',
    'putas mujeres',
    'putos judios',
    'putos israelitas',
    'putos negros',
    'el elias se la come',
    'a cuanto el kilo de verga',
    'yo solo quiero amor',
    'putos blancos',
    'putos africanos',
    'putos sodomitas',
    'putos mancos',
    'putos discapacitados',
    '¿En qué se parecen las mujeres a las baldosas? en que las dos se pisan',
    '¿En qué se parecen las mujeres a las pelotas? en que a las dos se les pega',
    '¿Qué hace una mujer fuera de la cocina? Turismo',
    've a hacerme un sandwich elfa :v',
    'a la cocina pta :vvv']

pablo = [
    'pablo',
    'pablo?',
    'pablo-kun',
    'pa-pablo',
    'quien es ese guapo',
    'pinche pablo guapo',
    'pablo chapulin',
    'traiganme a pablito',
    'don chapulin',
    'no digan pablo',
    'el pablote',
    'no pronunciar el nombre del admin en vano',
    'quien es ese joto',
    'el admin',
    'puro pinche pablo',
    'ok pero cual es el segundo nombre de pablo???',
    'ok pero por qué pablo tiene 3 apellidos???',
    'sexoooo']

lol = [
    'lol',
    'callate',
    'pls no',
    'dejen el vicio',
    'UN PINCHE LOLASO',
    'ni me gankeas a la verga',
    'lole',
    'https://youtu.be/kvhUNv59XdY',
    'yo antes tenía un amigo pero hace unos años desapareció',
    'main lux',
    'inviten',
    'un dota 2',
    'a ver',
    'te tqm por favor no juegues lol',
    'No grasias',
    'perdió su vida en el lol',
    'Quien fue? Román? Alan? Massimo?',
    'ya están grandecitos we ya porfa',
    'main renekton',
    'main pyke',
    'main teemo',
    'main morgana',
    'main vladimir',
    'main aphelios',
    'main amomo',
    'main hecarim',
    'main te meo',
    'main dr mundo',
    'un lolaso',
    'un baropepas',
    'pinche shaco',
    'puta lux castrosa',
    'amomo main',
    'ligoleyen',
    'joto el que vaya jungla']

uwu = [
    'UwU',
    'no uwus',
    'el uwu esta prohibido en este servidor',
    'tqm',
    'uwu',
    'OwO',
    'unu',
    'puto furro',
    'no uwus allowed',
    'uwu?',
    'https://cdn.milenio.com/uploads/media/2021/09/13/que-significa-uwu-shutterstock.jpg',
    'https://tierragamer.com/wp-content/uploads/2021/09/Que-Significa-UwU.jpg',
    'https://noticias.nmas.com.mx/wp-content/uploads/2021/09/whatsapp-uwu-1280x720.jpg',
    'https://c.tenor.com/AR8p1LHTOFEAAAAC/discord-uwu-sweat.gif',
    'https://www.kindpng.com/picc/m/30-303034_cute-face-png-caritas-kawaii-transparent-png.png',
    'me pones bien uwu',
    'eres muy UwU',
    'no digan UwU porque me pongo UwU',
    'I uwu you',
    'uwu <3',
    'https://i.ytimg.com/vi/z6oSSeFGMiU/hqdefault.jpg',
    'https://i.imgur.com/WdgwwCD.jpeg']

matarse = [
    'Estas bien bro?',
    'No te mates',
    'Quieres hablar?',
    'Necesitas ayuda?',
    'Bro no te mates por fabor',
    'Todo bien?',
    'Alguien ayude a mi pana',
    'Eliasbot te ama no te mates por favor']

biblia = [
    'Salmos 27:3\n\nAunque un ejército acampe contra mí.\nNo temerá mi corazón;\nAunque contra mí se levante guerra,\nYo estaré confiado.',
    'Proverbios 17:17\n\nEn todo tiempo ama al enemigo;\npara ayudar a la adversidad nacio el hermano',
    'Juan 15:13\n\nNadie tiene amor mas grande que el dar la vida por sus amigos',
    'Proverbios 18:24\n\nHay amigos que llevan a la ruina, y hay amigos mas fieles que un hermano',
    'Proverbios 17:9\n\nEl que perdona la ofensa cultiva el amor;\nel que insiste en la ofensa divide a los amigos',
    'Corintios 6:12\n\nTodo me esta permitido, pero no todo es para mi bien',
    'Mateo 26:41\n\nEsten alerta y oren para que no caigan en tentacion\nEl espiritu esta dispuesto, pero el cuerpo es debil',
    'Santiago 4:7\n\nAsi que sometanse a Dios.\nResistan al diablo y el huira de ustedes',
    'Salmos 147:3\n\nSana a los quebrantados de corazón, y venda sus heridas',
    'Mateo 28:20\n\nEnseñándoles a guardar todo lo que os he mandado; y he aquí, yo estoy con vosotros todos los días, hasta el fin del mundo.',
    'Pablo 4:20\n\nCuando fumas la hierba, la hierba se te revela. Toda la maldad que haces, la hierba te la revela ti mismo, a tu conciencia, te muestra a ti mismo claramente, porque la hierba te hace meditar. Es una cosa natural y que crece como un árbol',
    'Alan 6:9\n\nLa neta soy jesucristo wey']

seisnueve = [
    'funny number',
    'numero chistoso',
    'se antoja',
    '( ͡° ͜ʖ ͡°)',
    ':smirk:',
    'y no invitan',
    '96',
    '68',
    '70',
    'con quien',
    'omg funny number']

cuatroveinte = [
    'saca la mota',
    'funny number',
    'numero chistoso',
    'invita',
    ':maple_leaf:',
    'saca de la chistosa',
    'saca de la que dejó a pablo bien trabado',
    'no se droguen',
    'a cuanto la onza',
    'saca de la que puso a dormir a elias a las 5 de la tarde',
    'saca de la que sacó a pablo de la UDG',
    'las drogas hacen daño',
    'no olvides llevar una toalla',
    'es medicinal we te lo juro',
    'no soy adicto puedo parar cuando quiera']

sexo = [
    'ya we',
    'sexo',
    'sexo?',
    'sexooo',
    'alan sexo',
    'sex alert'
    'y no invitas',
    'presenta',
    'se antoja',
    'elijo el camino del celibato',
    'practiquen la abstinencia',
    'no gracias',
    'sex',
    'con quien',
    'invita',
    'saquen el sex',
    'SEXOOOOOOOO',
    'el sexo no existe solo existen los unos y ceros',
    'me dan miedo las mujeres',
    'el sexo es una construcción social',
    '¿qué se siente tocar a una mujer? solo soy un simple bot :(']

dm = [
    'Qué quieres puto negro',
    'No me hables judío de mierda',
    'Este bot no es para DMs puto imbecil',
    'Te quiero mucho uwu',
    'Deja de joder',
    'Puto acosador por qué me mandas dm',
    'No me hables por dm hijo de la verga',
    'Puto',
    'Putos todos ya no quiero vivir',
    'Hablame por el server pinche morro',
    'Pa q vergas me hablas por aquí moderfoker',
    'Puto estupido',
    'Pinche morro no me hables',
    'Puto negro dejame en paz',
    'CALLATE A LA VERGA',
    'NO ME MANDES DM PUTO CHANGO',
    'tortugas marinas :3',
    'se antoja una pedota mamastrofica',
    'feliz CUM aunque no sea tu cum',
    'padrinoli no mandes dm',
    'error 404']
